### ISSUE TITLE
Wrong handling of findall/sub (global) in Python for empty match

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#406]
In PCRE (or rather, the PHP wrapper), after an empty string match is found, the match is restarted at the same position, but with special flag to reject empty string match. If a non-empty string match is found, the current index will use the end index of the match. Only when it can't find a non-empty string match will it do the usual bump along.

However, in Python, there is no facility to reject empty string match. If an empty string is match, it will just follow the standard bump along behavior.

```
$ python3
Python 3.2.5 (default, Jul 25 2014, 14:13:17)
[GCC 4.8.3] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import re; re.findall(r'(.*?)', 'aaa')
['', '', '', '']
>>> import re; re.sub(r'(.*?)', 'x', 'aaa')
'xaxaxax'
```

Currently, regex101 does not replicate this behavior correctly in Python:

https://regex101.com/r/nQ5wR0/1

With regex `(.*?)` and input `aaa`, replacement `x`, regex101 currently returns 7 matches and the result of the replacement is `xxxxxxx` (which means that it follows the behavior of PCRE/PHP)

**Comment by firasdib** [comment]
Fixed in v2

**Comment by nhahtdh** [comment]
Reopen, since not fixed. Still see 7 matches.

**Comment by firasdib** [comment]
@nhahtdh Can not reproduce, see image

<img width="955" alt="screen shot 2016-08-23 at 10 20 10" src="https://cloud.githubusercontent.com/assets/1335165/17884945/377cdc44-691b-11e6-8e94-19cf23ea265c.png">

**Comment by nhahtdh** [comment]
It seems it happens when I switch back and forth between flavors, then back at Python. It has the correct result the first time, but when I come back from other flavors, it returns the wrong result.

I have do a hard refresh (Ctrl + Shift + R) and still see the issue.

**Comment by firasdib** [comment]
Nice find. It was a cache issue. Fixed now. Please verify and close.

**Comment by nhahtdh** [comment]
What the heck of a bug this is. Confirmed fixed. :+1:
